import os

JOB_LOG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Manual_Test_points_ALL_POINTS.csv")

DEF_X_MIN = 2.0
DEF_X_MAX = 8.0
DEF_TRIM_START = 0.0
DEF_TRIM_END = 0.0
DEF_MIN_WIDTH = 0.2
DEF_X_TOL = 1.2
DEF_MIN_CURV = 0.2
DEF_APEX_TOL = 0.5
DEF_MIN_PTS = 4
DEF_ALIGN_H = 0.5

DEF_PERC_MIN = 5
DEF_DELTA_H = 1.5

DEF_CONN_DX = 0.4
DEF_CONN_DY = 2.5   
DEF_CONN_DZ = 0.3   
DEF_MIN_SAMPLES = 1
DEF_MIN_CLUSTER_SIZE = 14
DEF_EPS = 1.0

DEF_MEDIAN_WINDOW = 5
DEF_MEDIAN_THRESHOLD = 0.9

DEF_SOR_K = 10
DEF_SOR_MULT = 1.0

DEF_EVAL_SPIKE_THR = 1.0
DEF_EVAL_FFT_CUTOFF = 0.25
DEF_EVAL_LAG = 1